/**
 * 500 player nicknames for the Arena Slaps game.
 *
 * Categories (100 each):
 * - Gamer tags (xX_Slap_Master_Xx, NoScopeSlapper, etc.)
 * - Funny/Silly (SirSlapsAlot, Slapahontas, etc.)
 * - Pop-culture references (SlapBaggins, SlapGandalf, etc.)
 * - Food/Things (PancakePuncher, WaffleWhacker, etc.)
 * - Animals (SlapDuck, PunchyPenguin, etc.)
 *
 * All names are screened against BANNED_WORDS. None contain racial slurs,
 * profanity, sexual content, hate speech, or violence-promoting terms.
 *
 * Used for:
 * - Bot names in 1P-vs-bot mode (random bot name each battle)
 * - Both player names in 2P-local mode (random names, no duplicates)
 */

// =============================================================================
// Category 1: Gamer tags (100)
// Style: xX_Name_Xx, NamePro, NameGG, NameSlapper, NameCombo, etc.
// =============================================================================
const GAMER_TAGS: readonly string[] = [
  "xX_Slap_Master_Xx",
  "xX_SlapGod_Xx",
  "xX_SlapLord_Xx",
  "xX_SlapBoss_Xx",
  "xX_SlapKing_Xx",
  "xX_SlapNinja_Xx",
  "xX_SlapSniper_Xx",
  "xX_SlapLegend_Xx",
  "xX_SlapChamp_Xx",
  "xX_SlapWizard_Xx",
  "xX_SlapBeast_Xx",
  "xX_SlapPhantom_Xx",
  "xX_SlapSlayer_Xx",
  "xX_SlapDemon_Xx",
  "xX_SlapDragon_Xx",
  "xX_SlapStorm_Xx",
  "xX_SlapFury_Xx",
  "xX_SlapKnight_Xx",
  "xX_SlapTitan_Xx",
  "xX_SlapWarlock_Xx",
  "NoScopeSlapper",
  "QuickScopeSlap",
  "SlapGod420",
  "SlapGod777",
  "SlapperKing",
  "ProSlapper",
  "SlapChamp",
  "EliteSlapper",
  "SlapLegend",
  "SlapNinja",
  "SlapWarrior",
  "SlapSniper",
  "SlapMaster99",
  "QuickSlap",
  "SlapGod",
  "SlapLord",
  "SlapBoss",
  "SlapPro",
  "TripleSlapCombo",
  "AimBotSlap",
  "SlapCombo",
  "SlapGG",
  "SlapEZ",
  "SlapFTW",
  "SlapOP",
  "SlapCarry",
  "SlapSmurf",
  "SlapClimb",
  "SlapRank",
  "SlapTier",
  "SlapStream",
  "SlapClip",
  "SlapMontage",
  "SlapHighlight",
  "SlapTournament",
  "SlapEsports",
  "SlapProGamer",
  "SlapStreamSniper",
  "SlapOneShot",
  "SlapNoScope",
  "Slap360",
  "SlapTrickshot",
  "SlapHeadshot",
  "SlapAimbot",
  "SlapWallbang",
  "SlapCamper",
  "SlapRusher",
  "SlapFlanker",
  "SlapHealer",
  "SlapTank",
  "SlapSupport",
  "SlapDPS",
  "SlapMidlaner",
  "SlapJungler",
  "SlapCarryGG",
  "SlapGGWP",
  "SlapGLHF",
  "SlapPogChamp",
  "SlapKekw",
  "SlapMonkaS",
  "SlapPepega",
  "SlapFeelsGood",
  "SlapSadge",
  "SlapPog",
  "SlapOmega",
  "SlapAlpha",
  "SlapBeta",
  "SlapGamma",
  "SlapDelta",
  "SlapSigma",
  "SlapPrime",
  "SlapApex",
  "SlapSummit",
  "SlapZenith",
  "SlapVertex",
  "SlapNexus",
  "SlapPrism",
  "SlapVector",
  "SlapQuantum",
  "SlapPhoenix",
];

// =============================================================================
// Category 2: Funny/Silly (100)
// Style: puns, wordplay, absurd combinations
// =============================================================================
const FUNNY_SILLY: readonly string[] = [
  "SirSlapsAlot",
  "Slapahontas",
  "CaptainClaptrap",
  "LordOfTheSlaps",
  "Slapzilla",
  "Slapopotamus",
  "SlapsterMind",
  "Slaponacci",
  "SlapDaddy",
  "SlapMommy",
  "SlapMachine",
  "SlapOmatic",
  "Slapdoodle",
  "Slapjack",
  "Slapoleon",
  "McSlap",
  "SlapFace",
  "SlapHappy",
  "SlapStick",
  "SlapChop",
  "SlapNovice",
  "SlapFest",
  "Slaparoo",
  "Slapathon",
  "Slapalicious",
  "Slapocalypse",
  "Slaptastic",
  "Slapowitz",
  "Slapinski",
  "Slapberg",
  "Slapenstein",
  "Slapovsky",
  "Slaparelli",
  "Slapucci",
  "Slapetto",
  "Slapowski",
  "Slapovitz",
  "Slapinstein",
  "Slapovski",
  "Slapspeare",
  "Slapenko",
  "Slapcasso",
  "Slapangelo",
  "Slapvinci",
  "Slapimedes",
  "Slapotle",
  "Slaplex",
  "Slapxander",
  "Slaprius",
  "Slapicus",
  "Slapulus",
  "Slapeth",
  "Slapford",
  "Slapbury",
  "Slapwick",
  "Slapstone",
  "Slapwood",
  "Slapton",
  "Slapfield",
  "Slapmoor",
  "Slapcliff",
  "Slapham",
  "Slapley",
  "Slapmere",
  "Slapwell",
  "Slapburn",
  "Slapcaster",
  "Slapwing",
  "Slapforge",
  "Slaphaven",
  "Slapridge",
  "Slapcrest",
  "Slaphollow",
  "Slapopolis",
  "Slapville",
  "Slapburg",
  "Slapland",
  "Slaplandia",
  "Slapdale",
  "Slapport",
  "Slapbridge",
  "Slapview",
  "Slapmore",
  "Slapby",
  "Slapster",
  "Slapnik",
  "Slapmaniac",
  "Slapaholic",
  "Slapophile",
  "Slapologist",
  "Slapocrite",
  "Slapocampus",
  "Slapacopter",
  "Slaparacha",
  "Slapadoop",
  "Slapnado",
  "Slapadillo",
  "Slapalope",
  "Slaparang",
  "Slapuccino",
];

// =============================================================================
// Category 3: Pop-culture references (100)
// Style: mashups of "Slap" + famous characters/quotes
// All names mashup "Slap" with the reference (no verbatim copyrighted names).
// =============================================================================
const POP_CULTURE: readonly string[] = [
  "SlapBaggins",
  "SlapGandalf",
  "TheSlapinator",
  "SlapSkywalker",
  "SlapPotter",
  "SlapStark",
  "SlapRogers",
  "SlapBros",
  "SuperSlap",
  "SlapMan",
  "BatSlap",
  "SpiderSlap",
  "SlapHulk",
  "SlapWidow",
  "SlapPanther",
  "SlapStrange",
  "SlapMarvel",
  "SlapDC",
  "SlapJedi",
  "SlapSith",
  "SlapVader",
  "SlapYoda",
  "SlapChewie",
  "SlapKenobi",
  "SlapSolo",
  "SlapFett",
  "SlapRen",
  "SlapTrooper",
  "SlapWookiee",
  "SlapR2",
  "Slap3PO",
  "SlapBB8",
  "SlapPicard",
  "SlapKirk",
  "SlapSpock",
  "SlapWorf",
  "SlapData",
  "SlapGeordi",
  "SlapUhura",
  "SlapSulu",
  "SlapChekov",
  "SlapScotty",
  "SlapBorg",
  "SlapKlingon",
  "SlapRomulan",
  "SlapVulcan",
  "SlapMatrix",
  "SlapNeo",
  "SlapTrinity",
  "SlapMorpheus",
  "SlapZion",
  "SlapOracle",
  "SlapSmith",
  "SlapArchitect",
  "SlapHogwarts",
  "SlapGryffindor",
  "SlapSlytherin",
  "SlapRavenclaw",
  "SlapHufflepuff",
  "SlapMuggle",
  "SlapQuidditch",
  "SlapSnitch",
  "SlapDobby",
  "SlapHedwig",
  "SlapVoldemort",
  "SlapMorty",
  "SlapRick",
  "SlapPickles",
  "SlapSquanchy",
  "SlapWubba",
  "SlapGoku",
  "SlapVegeta",
  "SlapPiccolo",
  "SlapKrillin",
  "SlapFrieza",
  "SlapCell",
  "SlapBuu",
  "SlapNaruto",
  "SlapSasuke",
  "SlapSakura",
  "SlapKakashi",
  "SlapItachi",
  "SlapPikachu",
  "SlapCharizard",
  "SlapBulbasaur",
  "SlapSquirtle",
  "SlapMewtwo",
  "SlapJigglypuff",
  "SlapSnorlax",
  "SlapEevee",
  "SlapThrones",
  "SlapJonSnow",
  "SlapDaenerys",
  "SlapTargaryen",
  "SlapLannister",
  "SlapTyrion",
  "SlapHodor",
  "SlapKhaleesi",
  "SlapWinterfell",
  "SlapWhitewalker",
];

// =============================================================================
// Category 4: Food/Things (100)
// Style: food + action, objects + slapper
// =============================================================================
const FOOD_THINGS: readonly string[] = [
  "PancakePuncher",
  "WaffleWhacker",
  "SlapSandwich",
  "BurritoBopper",
  "SlapSyrup",
  "SlapNoodle",
  "SlapPizza",
  "SlapBurger",
  "SlapTaco",
  "SlapSushi",
  "SlapDonut",
  "SlapBagel",
  "SlapMuffin",
  "SlapCookie",
  "SlapPretzel",
  "SlapPopcorn",
  "SlapWaffle",
  "SlapPancake",
  "SlapToast",
  "SlapBacon",
  "SlapEgg",
  "SlapOmelet",
  "SlapCheese",
  "SlapButter",
  "SlapMilk",
  "SlapCream",
  "SlapYogurt",
  "SlapPudding",
  "SlapJelly",
  "SlapJam",
  "SlapHoney",
  "SlapKetchup",
  "SlapMustard",
  "SlapRelish",
  "SlapMayo",
  "SlapDressing",
  "SlapGravy",
  "SlapSalsa",
  "SlapGuac",
  "SlapQueso",
  "SlapNacho",
  "SlapChili",
  "SlapCurry",
  "SlapRisotto",
  "SlapRamen",
  "SlapPho",
  "SlapUdon",
  "SlapSoba",
  "SlapPadThai",
  "SlapLoMein",
  "SlapChowMein",
  "SlapFriedRice",
  "SlapDumpling",
  "SlapMacaroni",
  "SlapRoastBeef",
  "SlapCereal",
  "SlapPasta",
  "SlapSpaghetti",
  "SlapFrenchFry",
  "SlapMushroom",
  "SlapSalad",
  "SlapSoup",
  "SlapStew",
  "SlapChowder",
  "SlapGumbo",
  "SlapBisque",
  "SlapBroth",
  "SlapBouillon",
  "SlapConsomme",
  "SlapMinestrone",
  "SlapLentil",
  "SlapSplitPea",
  "SlapTomato",
  "SlapBorscht",
  "SlapLaksa",
  "SlapTomYum",
  "SlapMiso",
  "SlapTempura",
  "SlapTeriyaki",
  "SlapWasabi",
  "SlapGinger",
  "SlapSoy",
  "SlapSriracha",
  "SlapTabasco",
  "SlapPepper",
  "SlapSalt",
  "SlapSugar",
  "SlapFlour",
  "SlapYeast",
  "SlapBakingSoda",
  "SlapVanilla",
  "SlapCinnamon",
  "SlapNutmeg",
  "SlapClove",
  "SlapCumin",
  "SlapPaprika",
  "SlapOregano",
  "SlapBasil",
  "SlapThyme",
  "SlapSage",
];

// =============================================================================
// Category 5: Animals (100)
// Style: animal + slap-related action
// =============================================================================
const ANIMALS: readonly string[] = [
  "SlapDuck",
  "PunchyPenguin",
  "SlapOwl",
  "WhackWalrus",
  "SlapTiger",
  "SlapBear",
  "SlapCat",
  "SlapDog",
  "SlapFox",
  "SlapWolf",
  "SlapLion",
  "SlapFrog",
  "SlapToad",
  "SlapFish",
  "SlapShark",
  "SlapWhale",
  "SlapDolphin",
  "SlapSeal",
  "SlapCrab",
  "SlapLobster",
  "SlapShrimp",
  "SlapSquid",
  "SlapOctopus",
  "SlapJellyfish",
  "SlapStarfish",
  "SlapSeahorse",
  "SlapEel",
  "SlapRay",
  "SlapTurtle",
  "SlapTortoise",
  "SlapSnake",
  "SlapCobra",
  "SlapPython",
  "SlapViper",
  "SlapGecko",
  "SlapLizard",
  "SlapIguana",
  "SlapChameleon",
  "SlapCrocodile",
  "SlapAlligator",
  "SlapEagle",
  "SlapHawk",
  "SlapFalcon",
  "SlapVulture",
  "SlapParrot",
  "SlapCrow",
  "SlapRaven",
  "SlapSparrow",
  "SlapRobin",
  "SlapPigeon",
  "SlapDove",
  "SlapSwan",
  "SlapGoose",
  "SlapPelican",
  "SlapFlamingo",
  "SlapPeafowl",
  "SlapTurkey",
  "SlapChicken",
  "SlapRooster",
  "SlapHen",
  "SlapChick",
  "SlapPuffin",
  "SlapMouse",
  "SlapRat",
  "SlapHamster",
  "SlapGerbil",
  "SlapGuineaPig",
  "SlapRabbit",
  "SlapChinchilla",
  "SlapHare",
  "SlapSquirrel",
  "SlapChipmunk",
  "SlapBeaver",
  "SlapHedgehog",
  "SlapPorcupine",
  "SlapBat",
  "SlapMole",
  "SlapBadger",
  "SlapOtter",
  "SlapFerret",
  "SlapWeasel",
  "SlapMink",
  "SlapMarten",
  "SlapWolverine",
  "SlapRaccoon",
  "SlapKoala",
  "SlapKangaroo",
  "SlapWallaby",
  "SlapPanda",
  "SlapRedPanda",
  "SlapSloth",
  "SlapAnteater",
  "SlapArmadillo",
  "SlapAardvark",
  "SlapPlatypus",
  "SlapEchidna",
  "SlapMonkey",
  "SlapGorilla",
  "SlapOrangutan",
  "SlapGibbon",
];

export const NICKNAMES: readonly string[] = [
  ...GAMER_TAGS,
  ...FUNNY_SILLY,
  ...POP_CULTURE,
  ...FOOD_THINGS,
  ...ANIMALS,
];

/**
 * Banned words used by {@link validateNickname}.
 *
 * Kept minimal but covering the obvious categories:
 * - Profanity
 * - Racial / hate-speech slurs
 * - Sexual terms
 * - Sexual-violence terms
 *
 * Note: short tokens like "ass" or "hell" are intentionally NOT included
 * because they appear as substrings of many innocent words ("class",
 * "shell", etc.). Longer, unambiguous forms ("asshole") are included.
 */
export const BANNED_WORDS: readonly string[] = [
  // Profanity
  "fuck",
  "shit",
  "bitch",
  "bastard",
  "cunt",
  "dick",
  "cock",
  "piss",
  "pussy",
  "asshole",
  "damn",
  "crap",
  // Sexual
  "slut",
  "whore",
  "horny",
  "nude",
  "porn",
  // Racial slurs / hate speech
  "nigger",
  "nigga",
  "chink",
  "spic",
  "kike",
  "faggot",
  "fag",
  "retard",
  "tranny",
  "nazi",
  "kkk",
  // Sexual violence
  "rape",
  "molest",
];

/**
 * Nickname returned by {@link getRandomNickname} when every entry in
 * {@link NICKNAMES} has been excluded. Kept simple and obviously safe.
 */
export const FALLBACK_NICKNAME = "Player";

/**
 * Get a random nickname from the list.
 * @param exclude - names to exclude (e.g. already-picked names in 2P mode)
 * @returns a random nickname not in the exclude list, or
 *          {@link FALLBACK_NICKNAME} if all names are excluded
 */
export function getRandomNickname(exclude?: string[]): string {
  const excludeSet = new Set(exclude ?? []);
  const available = NICKNAMES.filter((n) => !excludeSet.has(n));
  if (available.length === 0) {
    return FALLBACK_NICKNAME;
  }
  return available[Math.floor(Math.random() * available.length)];
}

/**
 * Get N random unique nicknames (no duplicates among them).
 * @param count - how many nicknames
 * @param exclude - additional names to exclude
 * @returns array of N unique nicknames. If `count` exceeds the number of
 *          available names, the returned array is shorter (capped at the
 *          available count). For `count <= 0`, an empty array is returned.
 */
export function getRandomNicknames(count: number, exclude?: string[]): string[] {
  if (count <= 0) return [];
  const excludeSet = new Set(exclude ?? []);
  const available = NICKNAMES.filter((n) => !excludeSet.has(n));
  // Fisher-Yates shuffle (in-place on the filtered copy)
  for (let i = available.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = available[i];
    available[i] = available[j];
    available[j] = tmp;
  }
  return available.slice(0, Math.min(count, available.length));
}

/**
 * Validate that a nickname doesn't contain any banned word
 * (case-insensitive substring match).
 * @returns true if the nickname is safe
 */
export function validateNickname(name: string): boolean {
  const lower = name.toLowerCase();
  return !BANNED_WORDS.some((word) => lower.includes(word));
}

/**
 * Total number of available nicknames. Equals `NICKNAMES.length` (500).
 */
export const NICKNAME_COUNT: number = NICKNAMES.length;
