/**
 * Pure nickname-resolution helper for the battle HUD.
 *
 * In 1P-vs-bot mode the player carries their profile nickname and the
 * opponent is a bot (with a random nickname generated by
 * {@link BattleSetupScene}). In 2P-local mode the player keeps the profile
 * nickname and the opponent is a second human whose nickname is also random.
 *
 * Extracted from {@link BattleScene.init} so the resolution rules can be
 * unit-tested without instantiating Phaser / the full scene. The defaults
 * match the fallbacks the scene already used before nicknames were wired in
 * ("Player" / "Bot" / "Player 2") so existing call sites that don't supply
 * a bot / player2 nickname keep working.
 */

export type NicknamePair = { player: string; opponent: string };

/**
 * Resolve the (player, opponent) nickname pair for the HUD + floating
 * labels from the scene data handed to {@link BattleScene.init}.
 *
 * @param mode              the active game mode (1P-vs-bot or 2P-local).
 * @param playerNickname    the profile nickname carried by the human player.
 * @param botNickname       the bot's random nickname (1P-vs-bot mode only).
 * @param player2Nickname   the second human's random nickname (2P-local only).
 * @returns `{ player, opponent }` with sensible defaults when either
 *          nickname is missing — `"Bot"` in 1P mode, `"Player 2"` in 2P mode.
 */
export function resolveNicknames(
  mode: "1p-vs-bot" | "2p-local",
  playerNickname: string,
  botNickname?: string,
  player2Nickname?: string,
): NicknamePair {
  if (mode === "2p-local") {
    return {
      player: playerNickname,
      opponent: player2Nickname ?? "Player 2",
    };
  }
  return {
    player: playerNickname,
    opponent: botNickname ?? "Bot",
  };
}
